{
 "title": "Netology",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Утилизация CPU для nodeexporter",
   "type": "timeseries",
   "description": "Утилизация CPU (100 - idle)",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "description": "Средняя загрузка CPU за 1, 5 и 15 минут.",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти.",
   "type": "timeseries",
   "description": "Количество свободной оперативной памяти.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024",
     "legendFormat": "Free RAM"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  (node_filesystem_avail_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\", fstype=\"ext4\"} * 100) /\r\n  node_filesystem_size_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\", fstype=\"ext4\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}